#!/bin/bash

#rm -rf /tmp/nvidia
#nvidia-settings -q GPUCoreTemp -t > /tmp/nvidia
#echo "nVidia"

TEMPERATURE=$(nvidia-settings -q GPUCoreTemp -t)

export CAIRO_DOCK_GPU_TEMP
CAIRO_DOCK_GPU_TEMP=$TEMPERATURE
