#!/bin/bash
rm -rf /tmp/nvidia
nvidia-settings -q Gpus | cut -d '(' -f 2 -s >> /tmp/nvidia
nvidia-settings -q VideoRam -t >> /tmp/nvidia
nvidia-settings -q NvidiaDriverVersion -t >> /tmp/nvidia
nvidia-settings -q GPUCoreTemp -t >> /tmp/nvidia
echo "nVidia"
