#!/bin/bash

if [ ! -w $1 ] ; then exit 1 ; fi
nvidia-settings -v | grep version | head -n 1 > $1
nvidia-settings -q Gpus | cut -d '(' -f 2 -s >> $1
nvidia-settings -q VideoRam -t >> $1
nvidia-settings -q NvidiaDriverVersion -t >> $1
