#!/usr/bin/python3

# This is a part of the external demo applet for Cairo-Dock
# Copyright : (C) 2010-2011 by Nochka85, Fabounet and atttbe
# E-mail : fabounet@glx-dock.org
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# ERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# http://www.gnu.org/licenses/licenses.html#GPL

# The name of this applet is "demo_bash"; it is placed in a folder named "demo_bash", with a file named "auto-load.conf" which describes it.
# Copy this folder into ~/.config/cairo-dock/third-party to let the dock register it automatically.
# In the folder we have :
# - "demo_bash"         : this python script, without extension
# - "demo_bash.sh"      : the script in bash, where you actually place your code
# - "demo_bash.conf"    : the config file of the applet
# - "auto-load.conf"    : the file describing the applet
# - "icon"              : the default icon of the applet (optionnal)
# - "preview"           : a preview of this applet (optionnal)

from CDBashApplet import CDBashApplet

if __name__ == '__main__':
	CDBashApplet().run()
