#!/bin/sh

# Compiz check for Cairo-Dock
#
# Copyright : (C) 2009 by Rémy Robertson
# E-mail    : fabounet@glx-dock.org
#
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# http://www.gnu.org/licenses/licenses.html#GPL

COMPIZ=$(pgrep compiz) || COMPIZ=0
XCOMPMGR=$(pgrep xcompmgr) || XCOMPMGR=0

if [ $COMPIZ -ne 0 ]; then
  kill $COMPIZ
fi
if [ $XCOMPMGR -ne 0 ]; then
  kill $XCOMPMGR
fi
