/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "interface-main-info.h"

#include <string.h>

/* ------------------------------------------------------------------------ */
/* Definitions for org.cairodock.CairoDock */

const GDBusMethodInfo org_cairodock_cairo_dock_interface__reboot_method =
{
  -1,  /* ref count */
  (gchar *) "Reboot",
  NULL,  /* no in args */
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusMethodInfo org_cairodock_cairo_dock_interface__quit_method =
{
  -1,  /* ref count */
  (gchar *) "Quit",
  NULL,  /* no in args */
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__show_dock_method_in_args__iVisibility_arg =
{
  -1,  /* ref count */
  (gchar *) "iVisibility",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_interface__show_dock_method_in_args[] =
{
  &org_cairodock_cairo_dock_interface__show_dock_method_in_args__iVisibility_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_interface__show_dock_method =
{
  -1,  /* ref count */
  (gchar *) "ShowDock",
  (GDBusArgInfo **) org_cairodock_cairo_dock_interface__show_dock_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__show_desklet_method_in_args__widgetLayer_arg =
{
  -1,  /* ref count */
  (gchar *) "widgetLayer",
  (gchar *) "b",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_interface__show_desklet_method_in_args[] =
{
  &org_cairodock_cairo_dock_interface__show_desklet_method_in_args__widgetLayer_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_interface__show_desklet_method =
{
  -1,  /* ref count */
  (gchar *) "ShowDesklet",
  (GDBusArgInfo **) org_cairodock_cairo_dock_interface__show_desklet_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__add_method_in_args__pProperties_arg =
{
  -1,  /* ref count */
  (gchar *) "pProperties",
  (gchar *) "a{sv}",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_interface__add_method_in_args[] =
{
  &org_cairodock_cairo_dock_interface__add_method_in_args__pProperties_arg,
  NULL,
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__add_method_out_args__cConfigFile_arg =
{
  -1,  /* ref count */
  (gchar *) "cConfigFile",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_interface__add_method_out_args[] =
{
  &org_cairodock_cairo_dock_interface__add_method_out_args__cConfigFile_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_interface__add_method =
{
  -1,  /* ref count */
  (gchar *) "Add",
  (GDBusArgInfo **) org_cairodock_cairo_dock_interface__add_method_in_args,
  (GDBusArgInfo **) org_cairodock_cairo_dock_interface__add_method_out_args,
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__reload_method_in_args__cQuery_arg =
{
  -1,  /* ref count */
  (gchar *) "cQuery",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_interface__reload_method_in_args[] =
{
  &org_cairodock_cairo_dock_interface__reload_method_in_args__cQuery_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_interface__reload_method =
{
  -1,  /* ref count */
  (gchar *) "Reload",
  (GDBusArgInfo **) org_cairodock_cairo_dock_interface__reload_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__remove_method_in_args__cQuery_arg =
{
  -1,  /* ref count */
  (gchar *) "cQuery",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_interface__remove_method_in_args[] =
{
  &org_cairodock_cairo_dock_interface__remove_method_in_args__cQuery_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_interface__remove_method =
{
  -1,  /* ref count */
  (gchar *) "Remove",
  (GDBusArgInfo **) org_cairodock_cairo_dock_interface__remove_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__get_properties_method_in_args__cQuery_arg =
{
  -1,  /* ref count */
  (gchar *) "cQuery",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_interface__get_properties_method_in_args[] =
{
  &org_cairodock_cairo_dock_interface__get_properties_method_in_args__cQuery_arg,
  NULL,
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__get_properties_method_out_args__pProperties_arg =
{
  -1,  /* ref count */
  (gchar *) "pProperties",
  (gchar *) "aa{sv}",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_interface__get_properties_method_out_args[] =
{
  &org_cairodock_cairo_dock_interface__get_properties_method_out_args__pProperties_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_interface__get_properties_method =
{
  -1,  /* ref count */
  (gchar *) "GetProperties",
  (GDBusArgInfo **) org_cairodock_cairo_dock_interface__get_properties_method_in_args,
  (GDBusArgInfo **) org_cairodock_cairo_dock_interface__get_properties_method_out_args,
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__set_quick_info_method_in_args__cQuickInfo_arg =
{
  -1,  /* ref count */
  (gchar *) "cQuickInfo",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__set_quick_info_method_in_args__cIconQuery_arg =
{
  -1,  /* ref count */
  (gchar *) "cIconQuery",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_interface__set_quick_info_method_in_args[] =
{
  &org_cairodock_cairo_dock_interface__set_quick_info_method_in_args__cQuickInfo_arg,
  &org_cairodock_cairo_dock_interface__set_quick_info_method_in_args__cIconQuery_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_interface__set_quick_info_method =
{
  -1,  /* ref count */
  (gchar *) "SetQuickInfo",
  (GDBusArgInfo **) org_cairodock_cairo_dock_interface__set_quick_info_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__set_label_method_in_args__cLabel_arg =
{
  -1,  /* ref count */
  (gchar *) "cLabel",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__set_label_method_in_args__cIconQuery_arg =
{
  -1,  /* ref count */
  (gchar *) "cIconQuery",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_interface__set_label_method_in_args[] =
{
  &org_cairodock_cairo_dock_interface__set_label_method_in_args__cLabel_arg,
  &org_cairodock_cairo_dock_interface__set_label_method_in_args__cIconQuery_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_interface__set_label_method =
{
  -1,  /* ref count */
  (gchar *) "SetLabel",
  (GDBusArgInfo **) org_cairodock_cairo_dock_interface__set_label_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__set_icon_method_in_args__cImage_arg =
{
  -1,  /* ref count */
  (gchar *) "cImage",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__set_icon_method_in_args__cIconQuery_arg =
{
  -1,  /* ref count */
  (gchar *) "cIconQuery",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_interface__set_icon_method_in_args[] =
{
  &org_cairodock_cairo_dock_interface__set_icon_method_in_args__cImage_arg,
  &org_cairodock_cairo_dock_interface__set_icon_method_in_args__cIconQuery_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_interface__set_icon_method =
{
  -1,  /* ref count */
  (gchar *) "SetIcon",
  (GDBusArgInfo **) org_cairodock_cairo_dock_interface__set_icon_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__set_emblem_method_in_args__cImage_arg =
{
  -1,  /* ref count */
  (gchar *) "cImage",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__set_emblem_method_in_args__iPosition_arg =
{
  -1,  /* ref count */
  (gchar *) "iPosition",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__set_emblem_method_in_args__cIconQuery_arg =
{
  -1,  /* ref count */
  (gchar *) "cIconQuery",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_interface__set_emblem_method_in_args[] =
{
  &org_cairodock_cairo_dock_interface__set_emblem_method_in_args__cImage_arg,
  &org_cairodock_cairo_dock_interface__set_emblem_method_in_args__iPosition_arg,
  &org_cairodock_cairo_dock_interface__set_emblem_method_in_args__cIconQuery_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_interface__set_emblem_method =
{
  -1,  /* ref count */
  (gchar *) "SetEmblem",
  (GDBusArgInfo **) org_cairodock_cairo_dock_interface__set_emblem_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__animate_method_in_args__cAnimation_arg =
{
  -1,  /* ref count */
  (gchar *) "cAnimation",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__animate_method_in_args__iNbRounds_arg =
{
  -1,  /* ref count */
  (gchar *) "iNbRounds",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__animate_method_in_args__cIconQuery_arg =
{
  -1,  /* ref count */
  (gchar *) "cIconQuery",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_interface__animate_method_in_args[] =
{
  &org_cairodock_cairo_dock_interface__animate_method_in_args__cAnimation_arg,
  &org_cairodock_cairo_dock_interface__animate_method_in_args__iNbRounds_arg,
  &org_cairodock_cairo_dock_interface__animate_method_in_args__cIconQuery_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_interface__animate_method =
{
  -1,  /* ref count */
  (gchar *) "Animate",
  (GDBusArgInfo **) org_cairodock_cairo_dock_interface__animate_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__demands_attention_method_in_args__bStart_arg =
{
  -1,  /* ref count */
  (gchar *) "bStart",
  (gchar *) "b",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__demands_attention_method_in_args__cAnimation_arg =
{
  -1,  /* ref count */
  (gchar *) "cAnimation",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__demands_attention_method_in_args__cIconQuery_arg =
{
  -1,  /* ref count */
  (gchar *) "cIconQuery",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_interface__demands_attention_method_in_args[] =
{
  &org_cairodock_cairo_dock_interface__demands_attention_method_in_args__bStart_arg,
  &org_cairodock_cairo_dock_interface__demands_attention_method_in_args__cAnimation_arg,
  &org_cairodock_cairo_dock_interface__demands_attention_method_in_args__cIconQuery_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_interface__demands_attention_method =
{
  -1,  /* ref count */
  (gchar *) "DemandsAttention",
  (GDBusArgInfo **) org_cairodock_cairo_dock_interface__demands_attention_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__show_dialog_method_in_args__message_arg =
{
  -1,  /* ref count */
  (gchar *) "message",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__show_dialog_method_in_args__iDuration_arg =
{
  -1,  /* ref count */
  (gchar *) "iDuration",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__show_dialog_method_in_args__cIconQuery_arg =
{
  -1,  /* ref count */
  (gchar *) "cIconQuery",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_interface__show_dialog_method_in_args[] =
{
  &org_cairodock_cairo_dock_interface__show_dialog_method_in_args__message_arg,
  &org_cairodock_cairo_dock_interface__show_dialog_method_in_args__iDuration_arg,
  &org_cairodock_cairo_dock_interface__show_dialog_method_in_args__cIconQuery_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_interface__show_dialog_method =
{
  -1,  /* ref count */
  (gchar *) "ShowDialog",
  (GDBusArgInfo **) org_cairodock_cairo_dock_interface__show_dialog_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__set_menu_method_in_args__cBusName_arg =
{
  -1,  /* ref count */
  (gchar *) "cBusName",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__set_menu_method_in_args__cMenuPath_arg =
{
  -1,  /* ref count */
  (gchar *) "cMenuPath",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__set_menu_method_in_args__cIconQuery_arg =
{
  -1,  /* ref count */
  (gchar *) "cIconQuery",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_interface__set_menu_method_in_args[] =
{
  &org_cairodock_cairo_dock_interface__set_menu_method_in_args__cBusName_arg,
  &org_cairodock_cairo_dock_interface__set_menu_method_in_args__cMenuPath_arg,
  &org_cairodock_cairo_dock_interface__set_menu_method_in_args__cIconQuery_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_interface__set_menu_method =
{
  -1,  /* ref count */
  (gchar *) "SetMenu",
  (GDBusArgInfo **) org_cairodock_cairo_dock_interface__set_menu_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__set_progress_method_in_args__fPercent_arg =
{
  -1,  /* ref count */
  (gchar *) "fPercent",
  (gchar *) "d",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_interface__set_progress_method_in_args__cIconQuery_arg =
{
  -1,  /* ref count */
  (gchar *) "cIconQuery",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_interface__set_progress_method_in_args[] =
{
  &org_cairodock_cairo_dock_interface__set_progress_method_in_args__fPercent_arg,
  &org_cairodock_cairo_dock_interface__set_progress_method_in_args__cIconQuery_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_interface__set_progress_method =
{
  -1,  /* ref count */
  (gchar *) "SetProgress",
  (GDBusArgInfo **) org_cairodock_cairo_dock_interface__set_progress_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusMethodInfo * const org_cairodock_cairo_dock_interface_methods[] =
{
  &org_cairodock_cairo_dock_interface__reboot_method,
  &org_cairodock_cairo_dock_interface__quit_method,
  &org_cairodock_cairo_dock_interface__show_dock_method,
  &org_cairodock_cairo_dock_interface__show_desklet_method,
  &org_cairodock_cairo_dock_interface__add_method,
  &org_cairodock_cairo_dock_interface__reload_method,
  &org_cairodock_cairo_dock_interface__remove_method,
  &org_cairodock_cairo_dock_interface__get_properties_method,
  &org_cairodock_cairo_dock_interface__set_quick_info_method,
  &org_cairodock_cairo_dock_interface__set_label_method,
  &org_cairodock_cairo_dock_interface__set_icon_method,
  &org_cairodock_cairo_dock_interface__set_emblem_method,
  &org_cairodock_cairo_dock_interface__animate_method,
  &org_cairodock_cairo_dock_interface__demands_attention_method,
  &org_cairodock_cairo_dock_interface__show_dialog_method,
  &org_cairodock_cairo_dock_interface__set_menu_method,
  &org_cairodock_cairo_dock_interface__set_progress_method,
  NULL,
};

const GDBusInterfaceInfo org_cairodock_cairo_dock_interface =
{
  -1,  /* ref count */
  (gchar *) "org.cairodock.CairoDock",
  (GDBusMethodInfo **) org_cairodock_cairo_dock_interface_methods,
  NULL,  /* no signals */
NULL,  /* no properties */
  NULL,  /* no annotations */
};

