/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "interface-sub-applet-info.h"

#include <string.h>

/* ------------------------------------------------------------------------ */
/* Definitions for org.cairodock.CairoDock.subapplet */

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__set_quick_info_method_in_args__cQuickInfo_arg =
{
  -1,  /* ref count */
  (gchar *) "cQuickInfo",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__set_quick_info_method_in_args__cIconID_arg =
{
  -1,  /* ref count */
  (gchar *) "cIconID",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_subapplet_interface__set_quick_info_method_in_args[] =
{
  &org_cairodock_cairo_dock_subapplet_interface__set_quick_info_method_in_args__cQuickInfo_arg,
  &org_cairodock_cairo_dock_subapplet_interface__set_quick_info_method_in_args__cIconID_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_subapplet_interface__set_quick_info_method =
{
  -1,  /* ref count */
  (gchar *) "SetQuickInfo",
  (GDBusArgInfo **) org_cairodock_cairo_dock_subapplet_interface__set_quick_info_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__set_label_method_in_args__cLabel_arg =
{
  -1,  /* ref count */
  (gchar *) "cLabel",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__set_label_method_in_args__cIconID_arg =
{
  -1,  /* ref count */
  (gchar *) "cIconID",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_subapplet_interface__set_label_method_in_args[] =
{
  &org_cairodock_cairo_dock_subapplet_interface__set_label_method_in_args__cLabel_arg,
  &org_cairodock_cairo_dock_subapplet_interface__set_label_method_in_args__cIconID_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_subapplet_interface__set_label_method =
{
  -1,  /* ref count */
  (gchar *) "SetLabel",
  (GDBusArgInfo **) org_cairodock_cairo_dock_subapplet_interface__set_label_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__set_icon_method_in_args__cImage_arg =
{
  -1,  /* ref count */
  (gchar *) "cImage",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__set_icon_method_in_args__cIconID_arg =
{
  -1,  /* ref count */
  (gchar *) "cIconID",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_subapplet_interface__set_icon_method_in_args[] =
{
  &org_cairodock_cairo_dock_subapplet_interface__set_icon_method_in_args__cImage_arg,
  &org_cairodock_cairo_dock_subapplet_interface__set_icon_method_in_args__cIconID_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_subapplet_interface__set_icon_method =
{
  -1,  /* ref count */
  (gchar *) "SetIcon",
  (GDBusArgInfo **) org_cairodock_cairo_dock_subapplet_interface__set_icon_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__set_emblem_method_in_args__cImage_arg =
{
  -1,  /* ref count */
  (gchar *) "cImage",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__set_emblem_method_in_args__iPosition_arg =
{
  -1,  /* ref count */
  (gchar *) "iPosition",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__set_emblem_method_in_args__cIconID_arg =
{
  -1,  /* ref count */
  (gchar *) "cIconID",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_subapplet_interface__set_emblem_method_in_args[] =
{
  &org_cairodock_cairo_dock_subapplet_interface__set_emblem_method_in_args__cImage_arg,
  &org_cairodock_cairo_dock_subapplet_interface__set_emblem_method_in_args__iPosition_arg,
  &org_cairodock_cairo_dock_subapplet_interface__set_emblem_method_in_args__cIconID_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_subapplet_interface__set_emblem_method =
{
  -1,  /* ref count */
  (gchar *) "SetEmblem",
  (GDBusArgInfo **) org_cairodock_cairo_dock_subapplet_interface__set_emblem_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__animate_method_in_args__cAnimation_arg =
{
  -1,  /* ref count */
  (gchar *) "cAnimation",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__animate_method_in_args__iNbRounds_arg =
{
  -1,  /* ref count */
  (gchar *) "iNbRounds",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__animate_method_in_args__cIconID_arg =
{
  -1,  /* ref count */
  (gchar *) "cIconID",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_subapplet_interface__animate_method_in_args[] =
{
  &org_cairodock_cairo_dock_subapplet_interface__animate_method_in_args__cAnimation_arg,
  &org_cairodock_cairo_dock_subapplet_interface__animate_method_in_args__iNbRounds_arg,
  &org_cairodock_cairo_dock_subapplet_interface__animate_method_in_args__cIconID_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_subapplet_interface__animate_method =
{
  -1,  /* ref count */
  (gchar *) "Animate",
  (GDBusArgInfo **) org_cairodock_cairo_dock_subapplet_interface__animate_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__show_dialog_method_in_args__message_arg =
{
  -1,  /* ref count */
  (gchar *) "message",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__show_dialog_method_in_args__iDuration_arg =
{
  -1,  /* ref count */
  (gchar *) "iDuration",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__show_dialog_method_in_args__cIconID_arg =
{
  -1,  /* ref count */
  (gchar *) "cIconID",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_subapplet_interface__show_dialog_method_in_args[] =
{
  &org_cairodock_cairo_dock_subapplet_interface__show_dialog_method_in_args__message_arg,
  &org_cairodock_cairo_dock_subapplet_interface__show_dialog_method_in_args__iDuration_arg,
  &org_cairodock_cairo_dock_subapplet_interface__show_dialog_method_in_args__cIconID_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_subapplet_interface__show_dialog_method =
{
  -1,  /* ref count */
  (gchar *) "ShowDialog",
  (GDBusArgInfo **) org_cairodock_cairo_dock_subapplet_interface__show_dialog_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__ask_question_method_in_args__cMessage_arg =
{
  -1,  /* ref count */
  (gchar *) "cMessage",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__ask_question_method_in_args__cIconID_arg =
{
  -1,  /* ref count */
  (gchar *) "cIconID",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_subapplet_interface__ask_question_method_in_args[] =
{
  &org_cairodock_cairo_dock_subapplet_interface__ask_question_method_in_args__cMessage_arg,
  &org_cairodock_cairo_dock_subapplet_interface__ask_question_method_in_args__cIconID_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_subapplet_interface__ask_question_method =
{
  -1,  /* ref count */
  (gchar *) "AskQuestion",
  (GDBusArgInfo **) org_cairodock_cairo_dock_subapplet_interface__ask_question_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__ask_value_method_in_args__cMessage_arg =
{
  -1,  /* ref count */
  (gchar *) "cMessage",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__ask_value_method_in_args__fInitialValue_arg =
{
  -1,  /* ref count */
  (gchar *) "fInitialValue",
  (gchar *) "d",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__ask_value_method_in_args__fMaxlValue_arg =
{
  -1,  /* ref count */
  (gchar *) "fMaxlValue",
  (gchar *) "d",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__ask_value_method_in_args__cIconID_arg =
{
  -1,  /* ref count */
  (gchar *) "cIconID",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_subapplet_interface__ask_value_method_in_args[] =
{
  &org_cairodock_cairo_dock_subapplet_interface__ask_value_method_in_args__cMessage_arg,
  &org_cairodock_cairo_dock_subapplet_interface__ask_value_method_in_args__fInitialValue_arg,
  &org_cairodock_cairo_dock_subapplet_interface__ask_value_method_in_args__fMaxlValue_arg,
  &org_cairodock_cairo_dock_subapplet_interface__ask_value_method_in_args__cIconID_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_subapplet_interface__ask_value_method =
{
  -1,  /* ref count */
  (gchar *) "AskValue",
  (GDBusArgInfo **) org_cairodock_cairo_dock_subapplet_interface__ask_value_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__ask_text_method_in_args__cMessage_arg =
{
  -1,  /* ref count */
  (gchar *) "cMessage",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__ask_text_method_in_args__cInitialText_arg =
{
  -1,  /* ref count */
  (gchar *) "cInitialText",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__ask_text_method_in_args__cIconID_arg =
{
  -1,  /* ref count */
  (gchar *) "cIconID",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_subapplet_interface__ask_text_method_in_args[] =
{
  &org_cairodock_cairo_dock_subapplet_interface__ask_text_method_in_args__cMessage_arg,
  &org_cairodock_cairo_dock_subapplet_interface__ask_text_method_in_args__cInitialText_arg,
  &org_cairodock_cairo_dock_subapplet_interface__ask_text_method_in_args__cIconID_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_subapplet_interface__ask_text_method =
{
  -1,  /* ref count */
  (gchar *) "AskText",
  (GDBusArgInfo **) org_cairodock_cairo_dock_subapplet_interface__ask_text_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__popup_dialog_method_in_args__hDialogAttributes_arg =
{
  -1,  /* ref count */
  (gchar *) "hDialogAttributes",
  (gchar *) "a{sv}",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__popup_dialog_method_in_args__hWidgetAttributes_arg =
{
  -1,  /* ref count */
  (gchar *) "hWidgetAttributes",
  (gchar *) "a{sv}",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__popup_dialog_method_in_args__cIconID_arg =
{
  -1,  /* ref count */
  (gchar *) "cIconID",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_subapplet_interface__popup_dialog_method_in_args[] =
{
  &org_cairodock_cairo_dock_subapplet_interface__popup_dialog_method_in_args__hDialogAttributes_arg,
  &org_cairodock_cairo_dock_subapplet_interface__popup_dialog_method_in_args__hWidgetAttributes_arg,
  &org_cairodock_cairo_dock_subapplet_interface__popup_dialog_method_in_args__cIconID_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_subapplet_interface__popup_dialog_method =
{
  -1,  /* ref count */
  (gchar *) "PopupDialog",
  (GDBusArgInfo **) org_cairodock_cairo_dock_subapplet_interface__popup_dialog_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__add_sub_icons_method_in_args__pIconFields_arg =
{
  -1,  /* ref count */
  (gchar *) "pIconFields",
  (gchar *) "as",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_subapplet_interface__add_sub_icons_method_in_args[] =
{
  &org_cairodock_cairo_dock_subapplet_interface__add_sub_icons_method_in_args__pIconFields_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_subapplet_interface__add_sub_icons_method =
{
  -1,  /* ref count */
  (gchar *) "AddSubIcons",
  (GDBusArgInfo **) org_cairodock_cairo_dock_subapplet_interface__add_sub_icons_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__remove_sub_icon_method_in_args__cIconID_arg =
{
  -1,  /* ref count */
  (gchar *) "cIconID",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_subapplet_interface__remove_sub_icon_method_in_args[] =
{
  &org_cairodock_cairo_dock_subapplet_interface__remove_sub_icon_method_in_args__cIconID_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_subapplet_interface__remove_sub_icon_method =
{
  -1,  /* ref count */
  (gchar *) "RemoveSubIcon",
  (GDBusArgInfo **) org_cairodock_cairo_dock_subapplet_interface__remove_sub_icon_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusMethodInfo * const org_cairodock_cairo_dock_subapplet_interface_methods[] =
{
  &org_cairodock_cairo_dock_subapplet_interface__set_quick_info_method,
  &org_cairodock_cairo_dock_subapplet_interface__set_label_method,
  &org_cairodock_cairo_dock_subapplet_interface__set_icon_method,
  &org_cairodock_cairo_dock_subapplet_interface__set_emblem_method,
  &org_cairodock_cairo_dock_subapplet_interface__animate_method,
  &org_cairodock_cairo_dock_subapplet_interface__show_dialog_method,
  &org_cairodock_cairo_dock_subapplet_interface__ask_question_method,
  &org_cairodock_cairo_dock_subapplet_interface__ask_value_method,
  &org_cairodock_cairo_dock_subapplet_interface__ask_text_method,
  &org_cairodock_cairo_dock_subapplet_interface__popup_dialog_method,
  &org_cairodock_cairo_dock_subapplet_interface__add_sub_icons_method,
  &org_cairodock_cairo_dock_subapplet_interface__remove_sub_icon_method,
  NULL,
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__on_click_sub_icon_signal_args__iButtonState_arg =
{
  -1,  /* ref count */
  (gchar *) "iButtonState",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__on_click_sub_icon_signal_args__cIconID_arg =
{
  -1,  /* ref count */
  (gchar *) "cIconID",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_subapplet_interface__on_click_sub_icon_signal_args[] =
{
  &org_cairodock_cairo_dock_subapplet_interface__on_click_sub_icon_signal_args__iButtonState_arg,
  &org_cairodock_cairo_dock_subapplet_interface__on_click_sub_icon_signal_args__cIconID_arg,
  NULL,
};

const GDBusSignalInfo org_cairodock_cairo_dock_subapplet_interface__on_click_sub_icon_signal =
{
  -1,  /* ref count */
  (gchar *) "on_click_sub_icon",
  (GDBusArgInfo **) org_cairodock_cairo_dock_subapplet_interface__on_click_sub_icon_signal_args,
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__on_middle_click_sub_icon_signal_args__cIconID_arg =
{
  -1,  /* ref count */
  (gchar *) "cIconID",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_subapplet_interface__on_middle_click_sub_icon_signal_args[] =
{
  &org_cairodock_cairo_dock_subapplet_interface__on_middle_click_sub_icon_signal_args__cIconID_arg,
  NULL,
};

const GDBusSignalInfo org_cairodock_cairo_dock_subapplet_interface__on_middle_click_sub_icon_signal =
{
  -1,  /* ref count */
  (gchar *) "on_middle_click_sub_icon",
  (GDBusArgInfo **) org_cairodock_cairo_dock_subapplet_interface__on_middle_click_sub_icon_signal_args,
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__on_scroll_sub_icon_signal_args__bDirectionUp_arg =
{
  -1,  /* ref count */
  (gchar *) "bDirectionUp",
  (gchar *) "b",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__on_scroll_sub_icon_signal_args__cIconID_arg =
{
  -1,  /* ref count */
  (gchar *) "cIconID",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_subapplet_interface__on_scroll_sub_icon_signal_args[] =
{
  &org_cairodock_cairo_dock_subapplet_interface__on_scroll_sub_icon_signal_args__bDirectionUp_arg,
  &org_cairodock_cairo_dock_subapplet_interface__on_scroll_sub_icon_signal_args__cIconID_arg,
  NULL,
};

const GDBusSignalInfo org_cairodock_cairo_dock_subapplet_interface__on_scroll_sub_icon_signal =
{
  -1,  /* ref count */
  (gchar *) "on_scroll_sub_icon",
  (GDBusArgInfo **) org_cairodock_cairo_dock_subapplet_interface__on_scroll_sub_icon_signal_args,
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__on_build_menu_sub_icon_signal_args__cIconID_arg =
{
  -1,  /* ref count */
  (gchar *) "cIconID",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_subapplet_interface__on_build_menu_sub_icon_signal_args[] =
{
  &org_cairodock_cairo_dock_subapplet_interface__on_build_menu_sub_icon_signal_args__cIconID_arg,
  NULL,
};

const GDBusSignalInfo org_cairodock_cairo_dock_subapplet_interface__on_build_menu_sub_icon_signal =
{
  -1,  /* ref count */
  (gchar *) "on_build_menu_sub_icon",
  (GDBusArgInfo **) org_cairodock_cairo_dock_subapplet_interface__on_build_menu_sub_icon_signal_args,
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__on_drop_data_sub_icon_signal_args__cReceivedData_arg =
{
  -1,  /* ref count */
  (gchar *) "cReceivedData",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_subapplet_interface__on_drop_data_sub_icon_signal_args__cIconID_arg =
{
  -1,  /* ref count */
  (gchar *) "cIconID",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_subapplet_interface__on_drop_data_sub_icon_signal_args[] =
{
  &org_cairodock_cairo_dock_subapplet_interface__on_drop_data_sub_icon_signal_args__cReceivedData_arg,
  &org_cairodock_cairo_dock_subapplet_interface__on_drop_data_sub_icon_signal_args__cIconID_arg,
  NULL,
};

const GDBusSignalInfo org_cairodock_cairo_dock_subapplet_interface__on_drop_data_sub_icon_signal =
{
  -1,  /* ref count */
  (gchar *) "on_drop_data_sub_icon",
  (GDBusArgInfo **) org_cairodock_cairo_dock_subapplet_interface__on_drop_data_sub_icon_signal_args,
  NULL,  /* no annotations */
};

const GDBusSignalInfo * const org_cairodock_cairo_dock_subapplet_interface_signals[] =
{
  &org_cairodock_cairo_dock_subapplet_interface__on_click_sub_icon_signal,
  &org_cairodock_cairo_dock_subapplet_interface__on_middle_click_sub_icon_signal,
  &org_cairodock_cairo_dock_subapplet_interface__on_scroll_sub_icon_signal,
  &org_cairodock_cairo_dock_subapplet_interface__on_build_menu_sub_icon_signal,
  &org_cairodock_cairo_dock_subapplet_interface__on_drop_data_sub_icon_signal,
  NULL,
};

const GDBusInterfaceInfo org_cairodock_cairo_dock_subapplet_interface =
{
  -1,  /* ref count */
  (gchar *) "org.cairodock.CairoDock.subapplet",
  (GDBusMethodInfo **) org_cairodock_cairo_dock_subapplet_interface_methods,
  (GDBusSignalInfo **) org_cairodock_cairo_dock_subapplet_interface_signals,
NULL,  /* no properties */
  NULL,  /* no annotations */
};

