/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifndef __INTERFACE_SUB_APPLET_INFO_H__
#define __INTERFACE_SUB_APPLET_INFO_H__

#include <gio/gio.h>

G_BEGIN_DECLS

extern  const GDBusInterfaceInfo org_cairodock_cairo_dock_subapplet_interface;

G_END_DECLS

#endif /* __INTERFACE_SUB_APPLET_INFO_H__ */
