/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "interface-applet-info.h"

#include <string.h>

/* ------------------------------------------------------------------------ */
/* Definitions for org.cairodock.CairoDock.applet */

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__get_method_in_args__cProperty_arg =
{
  -1,  /* ref count */
  (gchar *) "cProperty",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__get_method_in_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__get_method_in_args__cProperty_arg,
  NULL,
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__get_method_out_args__value_arg =
{
  -1,  /* ref count */
  (gchar *) "value",
  (gchar *) "v",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__get_method_out_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__get_method_out_args__value_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_applet_interface__get_method =
{
  -1,  /* ref count */
  (gchar *) "Get",
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__get_method_in_args,
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__get_method_out_args,
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__get_all_method_out_args__hProperties_arg =
{
  -1,  /* ref count */
  (gchar *) "hProperties",
  (gchar *) "a{sv}",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__get_all_method_out_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__get_all_method_out_args__hProperties_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_applet_interface__get_all_method =
{
  -1,  /* ref count */
  (gchar *) "GetAll",
  NULL,  /* no in args */
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__get_all_method_out_args,
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__set_quick_info_method_in_args__cQuickInfo_arg =
{
  -1,  /* ref count */
  (gchar *) "cQuickInfo",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__set_quick_info_method_in_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__set_quick_info_method_in_args__cQuickInfo_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_applet_interface__set_quick_info_method =
{
  -1,  /* ref count */
  (gchar *) "SetQuickInfo",
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__set_quick_info_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__set_label_method_in_args__cLabel_arg =
{
  -1,  /* ref count */
  (gchar *) "cLabel",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__set_label_method_in_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__set_label_method_in_args__cLabel_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_applet_interface__set_label_method =
{
  -1,  /* ref count */
  (gchar *) "SetLabel",
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__set_label_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__set_icon_method_in_args__cImage_arg =
{
  -1,  /* ref count */
  (gchar *) "cImage",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__set_icon_method_in_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__set_icon_method_in_args__cImage_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_applet_interface__set_icon_method =
{
  -1,  /* ref count */
  (gchar *) "SetIcon",
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__set_icon_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__set_emblem_method_in_args__cImage_arg =
{
  -1,  /* ref count */
  (gchar *) "cImage",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__set_emblem_method_in_args__iPosition_arg =
{
  -1,  /* ref count */
  (gchar *) "iPosition",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__set_emblem_method_in_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__set_emblem_method_in_args__cImage_arg,
  &org_cairodock_cairo_dock_applet_interface__set_emblem_method_in_args__iPosition_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_applet_interface__set_emblem_method =
{
  -1,  /* ref count */
  (gchar *) "SetEmblem",
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__set_emblem_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__animate_method_in_args__cAnimation_arg =
{
  -1,  /* ref count */
  (gchar *) "cAnimation",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__animate_method_in_args__iNbRounds_arg =
{
  -1,  /* ref count */
  (gchar *) "iNbRounds",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__animate_method_in_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__animate_method_in_args__cAnimation_arg,
  &org_cairodock_cairo_dock_applet_interface__animate_method_in_args__iNbRounds_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_applet_interface__animate_method =
{
  -1,  /* ref count */
  (gchar *) "Animate",
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__animate_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__demands_attention_method_in_args__bStart_arg =
{
  -1,  /* ref count */
  (gchar *) "bStart",
  (gchar *) "b",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__demands_attention_method_in_args__cAnimation_arg =
{
  -1,  /* ref count */
  (gchar *) "cAnimation",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__demands_attention_method_in_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__demands_attention_method_in_args__bStart_arg,
  &org_cairodock_cairo_dock_applet_interface__demands_attention_method_in_args__cAnimation_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_applet_interface__demands_attention_method =
{
  -1,  /* ref count */
  (gchar *) "DemandsAttention",
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__demands_attention_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__show_dialog_method_in_args__cMessage_arg =
{
  -1,  /* ref count */
  (gchar *) "cMessage",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__show_dialog_method_in_args__iDuration_arg =
{
  -1,  /* ref count */
  (gchar *) "iDuration",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__show_dialog_method_in_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__show_dialog_method_in_args__cMessage_arg,
  &org_cairodock_cairo_dock_applet_interface__show_dialog_method_in_args__iDuration_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_applet_interface__show_dialog_method =
{
  -1,  /* ref count */
  (gchar *) "ShowDialog",
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__show_dialog_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__popup_dialog_method_in_args__hDialogAttributes_arg =
{
  -1,  /* ref count */
  (gchar *) "hDialogAttributes",
  (gchar *) "a{sv}",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__popup_dialog_method_in_args__hWidgetAttributes_arg =
{
  -1,  /* ref count */
  (gchar *) "hWidgetAttributes",
  (gchar *) "a{sv}",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__popup_dialog_method_in_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__popup_dialog_method_in_args__hDialogAttributes_arg,
  &org_cairodock_cairo_dock_applet_interface__popup_dialog_method_in_args__hWidgetAttributes_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_applet_interface__popup_dialog_method =
{
  -1,  /* ref count */
  (gchar *) "PopupDialog",
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__popup_dialog_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__add_data_renderer_method_in_args__cType_arg =
{
  -1,  /* ref count */
  (gchar *) "cType",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__add_data_renderer_method_in_args__iNbValues_arg =
{
  -1,  /* ref count */
  (gchar *) "iNbValues",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__add_data_renderer_method_in_args__cTheme_arg =
{
  -1,  /* ref count */
  (gchar *) "cTheme",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__add_data_renderer_method_in_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__add_data_renderer_method_in_args__cType_arg,
  &org_cairodock_cairo_dock_applet_interface__add_data_renderer_method_in_args__iNbValues_arg,
  &org_cairodock_cairo_dock_applet_interface__add_data_renderer_method_in_args__cTheme_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_applet_interface__add_data_renderer_method =
{
  -1,  /* ref count */
  (gchar *) "AddDataRenderer",
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__add_data_renderer_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__render_values_method_in_args__pValues_arg =
{
  -1,  /* ref count */
  (gchar *) "pValues",
  (gchar *) "ad",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__render_values_method_in_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__render_values_method_in_args__pValues_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_applet_interface__render_values_method =
{
  -1,  /* ref count */
  (gchar *) "RenderValues",
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__render_values_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__control_appli_method_in_args__cApplicationClass_arg =
{
  -1,  /* ref count */
  (gchar *) "cApplicationClass",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__control_appli_method_in_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__control_appli_method_in_args__cApplicationClass_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_applet_interface__control_appli_method =
{
  -1,  /* ref count */
  (gchar *) "ControlAppli",
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__control_appli_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__act_on_appli_method_in_args__cAction_arg =
{
  -1,  /* ref count */
  (gchar *) "cAction",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__act_on_appli_method_in_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__act_on_appli_method_in_args__cAction_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_applet_interface__act_on_appli_method =
{
  -1,  /* ref count */
  (gchar *) "ActOnAppli",
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__act_on_appli_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__add_menu_items_method_in_args__pItems_arg =
{
  -1,  /* ref count */
  (gchar *) "pItems",
  (gchar *) "aa{sv}",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__add_menu_items_method_in_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__add_menu_items_method_in_args__pItems_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_applet_interface__add_menu_items_method =
{
  -1,  /* ref count */
  (gchar *) "AddMenuItems",
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__add_menu_items_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__bind_shortkey_method_in_args__cShortkeys_arg =
{
  -1,  /* ref count */
  (gchar *) "cShortkeys",
  (gchar *) "as",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__bind_shortkey_method_in_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__bind_shortkey_method_in_args__cShortkeys_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_applet_interface__bind_shortkey_method =
{
  -1,  /* ref count */
  (gchar *) "BindShortkey",
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__bind_shortkey_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__ask_question_method_in_args__cMessage_arg =
{
  -1,  /* ref count */
  (gchar *) "cMessage",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__ask_question_method_in_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__ask_question_method_in_args__cMessage_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_applet_interface__ask_question_method =
{
  -1,  /* ref count */
  (gchar *) "AskQuestion",
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__ask_question_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__ask_value_method_in_args__cMessage_arg =
{
  -1,  /* ref count */
  (gchar *) "cMessage",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__ask_value_method_in_args__fInitialValue_arg =
{
  -1,  /* ref count */
  (gchar *) "fInitialValue",
  (gchar *) "d",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__ask_value_method_in_args__fMaxlValue_arg =
{
  -1,  /* ref count */
  (gchar *) "fMaxlValue",
  (gchar *) "d",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__ask_value_method_in_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__ask_value_method_in_args__cMessage_arg,
  &org_cairodock_cairo_dock_applet_interface__ask_value_method_in_args__fInitialValue_arg,
  &org_cairodock_cairo_dock_applet_interface__ask_value_method_in_args__fMaxlValue_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_applet_interface__ask_value_method =
{
  -1,  /* ref count */
  (gchar *) "AskValue",
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__ask_value_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__ask_text_method_in_args__cMessage_arg =
{
  -1,  /* ref count */
  (gchar *) "cMessage",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__ask_text_method_in_args__cInitialText_arg =
{
  -1,  /* ref count */
  (gchar *) "cInitialText",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__ask_text_method_in_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__ask_text_method_in_args__cMessage_arg,
  &org_cairodock_cairo_dock_applet_interface__ask_text_method_in_args__cInitialText_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_applet_interface__ask_text_method =
{
  -1,  /* ref count */
  (gchar *) "AskText",
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__ask_text_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__show_appli_method_in_args__bShow_arg =
{
  -1,  /* ref count */
  (gchar *) "bShow",
  (gchar *) "b",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__show_appli_method_in_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__show_appli_method_in_args__bShow_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_applet_interface__show_appli_method =
{
  -1,  /* ref count */
  (gchar *) "ShowAppli",
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__show_appli_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__populate_menu_method_in_args__pLabels_arg =
{
  -1,  /* ref count */
  (gchar *) "pLabels",
  (gchar *) "as",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__populate_menu_method_in_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__populate_menu_method_in_args__pLabels_arg,
  NULL,
};

const GDBusMethodInfo org_cairodock_cairo_dock_applet_interface__populate_menu_method =
{
  -1,  /* ref count */
  (gchar *) "PopulateMenu",
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__populate_menu_method_in_args,
  NULL,  /* no out args */
  NULL,  /* no annotations */
};

const GDBusMethodInfo * const org_cairodock_cairo_dock_applet_interface_methods[] =
{
  &org_cairodock_cairo_dock_applet_interface__get_method,
  &org_cairodock_cairo_dock_applet_interface__get_all_method,
  &org_cairodock_cairo_dock_applet_interface__set_quick_info_method,
  &org_cairodock_cairo_dock_applet_interface__set_label_method,
  &org_cairodock_cairo_dock_applet_interface__set_icon_method,
  &org_cairodock_cairo_dock_applet_interface__set_emblem_method,
  &org_cairodock_cairo_dock_applet_interface__animate_method,
  &org_cairodock_cairo_dock_applet_interface__demands_attention_method,
  &org_cairodock_cairo_dock_applet_interface__show_dialog_method,
  &org_cairodock_cairo_dock_applet_interface__popup_dialog_method,
  &org_cairodock_cairo_dock_applet_interface__add_data_renderer_method,
  &org_cairodock_cairo_dock_applet_interface__render_values_method,
  &org_cairodock_cairo_dock_applet_interface__control_appli_method,
  &org_cairodock_cairo_dock_applet_interface__act_on_appli_method,
  &org_cairodock_cairo_dock_applet_interface__add_menu_items_method,
  &org_cairodock_cairo_dock_applet_interface__bind_shortkey_method,
  &org_cairodock_cairo_dock_applet_interface__ask_question_method,
  &org_cairodock_cairo_dock_applet_interface__ask_value_method,
  &org_cairodock_cairo_dock_applet_interface__ask_text_method,
  &org_cairodock_cairo_dock_applet_interface__show_appli_method,
  &org_cairodock_cairo_dock_applet_interface__populate_menu_method,
  NULL,
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__on_click_signal_args__iButtonState_arg =
{
  -1,  /* ref count */
  (gchar *) "iButtonState",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__on_click_signal_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__on_click_signal_args__iButtonState_arg,
  NULL,
};

const GDBusSignalInfo org_cairodock_cairo_dock_applet_interface__on_click_signal =
{
  -1,  /* ref count */
  (gchar *) "on_click",
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__on_click_signal_args,
  NULL,  /* no annotations */
};

const GDBusSignalInfo org_cairodock_cairo_dock_applet_interface__on_middle_click_signal =
{
  -1,  /* ref count */
  (gchar *) "on_middle_click",
  NULL,  /* no args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__on_scroll_signal_args__bDirectionUp_arg =
{
  -1,  /* ref count */
  (gchar *) "bDirectionUp",
  (gchar *) "b",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__on_scroll_signal_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__on_scroll_signal_args__bDirectionUp_arg,
  NULL,
};

const GDBusSignalInfo org_cairodock_cairo_dock_applet_interface__on_scroll_signal =
{
  -1,  /* ref count */
  (gchar *) "on_scroll",
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__on_scroll_signal_args,
  NULL,  /* no annotations */
};

const GDBusSignalInfo org_cairodock_cairo_dock_applet_interface__on_build_menu_signal =
{
  -1,  /* ref count */
  (gchar *) "on_build_menu",
  NULL,  /* no args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__on_menu_select_signal_args__iNumEntry_arg =
{
  -1,  /* ref count */
  (gchar *) "iNumEntry",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__on_menu_select_signal_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__on_menu_select_signal_args__iNumEntry_arg,
  NULL,
};

const GDBusSignalInfo org_cairodock_cairo_dock_applet_interface__on_menu_select_signal =
{
  -1,  /* ref count */
  (gchar *) "on_menu_select",
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__on_menu_select_signal_args,
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__on_drop_data_signal_args__cReceivedData_arg =
{
  -1,  /* ref count */
  (gchar *) "cReceivedData",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__on_drop_data_signal_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__on_drop_data_signal_args__cReceivedData_arg,
  NULL,
};

const GDBusSignalInfo org_cairodock_cairo_dock_applet_interface__on_drop_data_signal =
{
  -1,  /* ref count */
  (gchar *) "on_drop_data",
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__on_drop_data_signal_args,
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__on_change_focus_signal_args__is_active_arg =
{
  -1,  /* ref count */
  (gchar *) "is_active",
  (gchar *) "b",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__on_change_focus_signal_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__on_change_focus_signal_args__is_active_arg,
  NULL,
};

const GDBusSignalInfo org_cairodock_cairo_dock_applet_interface__on_change_focus_signal =
{
  -1,  /* ref count */
  (gchar *) "on_change_focus",
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__on_change_focus_signal_args,
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__on_answer_signal_args__answer_arg =
{
  -1,  /* ref count */
  (gchar *) "answer",
  (gchar *) "v",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__on_answer_signal_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__on_answer_signal_args__answer_arg,
  NULL,
};

const GDBusSignalInfo org_cairodock_cairo_dock_applet_interface__on_answer_signal =
{
  -1,  /* ref count */
  (gchar *) "on_answer",
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__on_answer_signal_args,
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__on_answer_dialog_signal_args__iClickedButton_arg =
{
  -1,  /* ref count */
  (gchar *) "iClickedButton",
  (gchar *) "i",
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__on_answer_dialog_signal_args__answer_arg =
{
  -1,  /* ref count */
  (gchar *) "answer",
  (gchar *) "v",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__on_answer_dialog_signal_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__on_answer_dialog_signal_args__iClickedButton_arg,
  &org_cairodock_cairo_dock_applet_interface__on_answer_dialog_signal_args__answer_arg,
  NULL,
};

const GDBusSignalInfo org_cairodock_cairo_dock_applet_interface__on_answer_dialog_signal =
{
  -1,  /* ref count */
  (gchar *) "on_answer_dialog",
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__on_answer_dialog_signal_args,
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__on_shortkey_signal_args__cShortkey_arg =
{
  -1,  /* ref count */
  (gchar *) "cShortkey",
  (gchar *) "s",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__on_shortkey_signal_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__on_shortkey_signal_args__cShortkey_arg,
  NULL,
};

const GDBusSignalInfo org_cairodock_cairo_dock_applet_interface__on_shortkey_signal =
{
  -1,  /* ref count */
  (gchar *) "on_shortkey",
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__on_shortkey_signal_args,
  NULL,  /* no annotations */
};

const GDBusSignalInfo org_cairodock_cairo_dock_applet_interface__on_stop_module_signal =
{
  -1,  /* ref count */
  (gchar *) "on_stop_module",
  NULL,  /* no args */
  NULL,  /* no annotations */
};

const GDBusArgInfo org_cairodock_cairo_dock_applet_interface__on_reload_module_signal_args__bConfigHasChanged_arg =
{
  -1,  /* ref count */
  (gchar *) "bConfigHasChanged",
  (gchar *) "b",
  NULL,  /* no annotations */
};

const GDBusArgInfo * const org_cairodock_cairo_dock_applet_interface__on_reload_module_signal_args[] =
{
  &org_cairodock_cairo_dock_applet_interface__on_reload_module_signal_args__bConfigHasChanged_arg,
  NULL,
};

const GDBusSignalInfo org_cairodock_cairo_dock_applet_interface__on_reload_module_signal =
{
  -1,  /* ref count */
  (gchar *) "on_reload_module",
  (GDBusArgInfo **) org_cairodock_cairo_dock_applet_interface__on_reload_module_signal_args,
  NULL,  /* no annotations */
};

const GDBusSignalInfo * const org_cairodock_cairo_dock_applet_interface_signals[] =
{
  &org_cairodock_cairo_dock_applet_interface__on_click_signal,
  &org_cairodock_cairo_dock_applet_interface__on_middle_click_signal,
  &org_cairodock_cairo_dock_applet_interface__on_scroll_signal,
  &org_cairodock_cairo_dock_applet_interface__on_build_menu_signal,
  &org_cairodock_cairo_dock_applet_interface__on_menu_select_signal,
  &org_cairodock_cairo_dock_applet_interface__on_drop_data_signal,
  &org_cairodock_cairo_dock_applet_interface__on_change_focus_signal,
  &org_cairodock_cairo_dock_applet_interface__on_answer_signal,
  &org_cairodock_cairo_dock_applet_interface__on_answer_dialog_signal,
  &org_cairodock_cairo_dock_applet_interface__on_shortkey_signal,
  &org_cairodock_cairo_dock_applet_interface__on_stop_module_signal,
  &org_cairodock_cairo_dock_applet_interface__on_reload_module_signal,
  NULL,
};

const GDBusPropertyInfo org_cairodock_cairo_dock_applet_interface__x_property =
{
  -1,  /* ref count */
  (gchar *) "x",
  (gchar *) "i",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_cairodock_cairo_dock_applet_interface__y_property =
{
  -1,  /* ref count */
  (gchar *) "y",
  (gchar *) "i",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_cairodock_cairo_dock_applet_interface__width_property =
{
  -1,  /* ref count */
  (gchar *) "width",
  (gchar *) "i",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_cairodock_cairo_dock_applet_interface__height_property =
{
  -1,  /* ref count */
  (gchar *) "height",
  (gchar *) "i",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_cairodock_cairo_dock_applet_interface__orientation_property =
{
  -1,  /* ref count */
  (gchar *) "orientation",
  (gchar *) "u",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_cairodock_cairo_dock_applet_interface__container_property =
{
  -1,  /* ref count */
  (gchar *) "container",
  (gchar *) "u",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_cairodock_cairo_dock_applet_interface__xid_property =
{
  -1,  /* ref count */
  (gchar *) "Xid",
  (gchar *) "t",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo org_cairodock_cairo_dock_applet_interface__has_focus_property =
{
  -1,  /* ref count */
  (gchar *) "has_focus",
  (gchar *) "b",
  G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
  NULL,  /* no annotations */
};

const GDBusPropertyInfo * const org_cairodock_cairo_dock_applet_interface_properties[] =
{
  &org_cairodock_cairo_dock_applet_interface__x_property,
  &org_cairodock_cairo_dock_applet_interface__y_property,
  &org_cairodock_cairo_dock_applet_interface__width_property,
  &org_cairodock_cairo_dock_applet_interface__height_property,
  &org_cairodock_cairo_dock_applet_interface__orientation_property,
  &org_cairodock_cairo_dock_applet_interface__container_property,
  &org_cairodock_cairo_dock_applet_interface__xid_property,
  &org_cairodock_cairo_dock_applet_interface__has_focus_property,
  NULL,
};

const GDBusInterfaceInfo org_cairodock_cairo_dock_applet_interface =
{
  -1,  /* ref count */
  (gchar *) "org.cairodock.CairoDock.applet",
  (GDBusMethodInfo **) org_cairodock_cairo_dock_applet_interface_methods,
  (GDBusSignalInfo **) org_cairodock_cairo_dock_applet_interface_signals,
  (GDBusPropertyInfo **) org_cairodock_cairo_dock_applet_interface_properties,
  NULL,  /* no annotations */
};

